name: CI/CD a Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar TypeScript
        run: npm run build

      - name: Autenticarse en Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configurar Docker para GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Construir y subir imagen a Artifact Registry
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastify-ts-cicd

      - name: Desplegar a Cloud Run
        run: |
          gcloud run deploy fastify-ts-cicd \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastify-ts-cicd \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
